### ISSUE TITLE
WMS Struct Window

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#11]
## Description
Ein Struct das zur Kontrolle und für Funktionalitäten von Fenstern ist.

## Details
Projekt: "ecm.window.dll"
Datei: "window.h" "window.cpp"
Namespace: "ecm"

## Tasks
- [x] struct Window
- [x] Variable id_type _id
- [x] Methode bool IsValid
- [x] Methode id_type GetID
- [x] Methode void* Handle
- [x] Methode void SetFullscreen
- [x] Methode bool IsFullscreen
- [x] Methode bool IsFocused
- [x] Methode void SetCaption
- [x] Methode const char* Caption
- [x] Methode void SetPosition
- [x] Methode int32 PositionX
- [x] Methode int32 PositionY
- [x] Methode void Resize
- [x] Methode uint32 Width
- [x] Methode uint32 Height
