### ISSUE TITLE
WMS anonyme Funktionen und Variablen implementieren

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#12]
## Description
Die anonymen Funktionen als Inline-Funktionen implementieren.

## Details
Projekt: "ecm.window.dll"
Datei: "window.h"
Namespace: "ecm"

## Tasks
- [x] Funktion void SetFullscreen
- [x] Funktion bool IsFullscreen
- [x] Funktion bool IsFocused
- [x] Funktion void SetCaption
- [x] Funktion const char* Caption
- [x] Funktion void SetPosition
- [x] Funktion int32 PositionX
- [x] Funktion int32 PositionY
- [x] Funktion void Resize
- [x] Funktion uint32 Width
- [x] Funktion uint32 Height
