### ISSUE TITLE
WMS Methoden von Window mit anonymen Funktionen bestücken

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#13]
## Description
Die anonymen Funktionen in den Methoden des Window-Structes implementieren.

## Details
Projekt: "ecm.window.dll"
Datei: "window.h" "window.cpp"
Namespace: "ecm"

## Tasks
- [x] Funktion void SetMode
- [x] Funktion bool GetMode
- [x] Funktion bool GetFocused
- [x] Funktion void SetFocus
- [x] Funktion void SetCaption
- [x] Funktion const char* Caption
- [x] Funktion void SetPosition
- [x] Funktion Point GetPosition
- [x] Funktion void Resize
- [x] Funktion Point GetSize
