### ISSUE TITLE
SDL2 einbinden und linken

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#14]
## Description
Die neueste Version von SDL2 herunterladen und in das Projekt einbinden.

## Details
Projekt: "ecm.window.dll"
Datei: "dllmain.cpp"
Namespace: -

## Tasks
- [x] Neueste Version von SDL2 herunterladen
- [x] SDL2 Header in /vendor kopieren
- [x] SDL2 .dll und .lib in die Debug-/Release-Ordner kopieren
- [x] SDL2.lib in dllmain.cpp linken
