### ISSUE TITLE
Color-Struct Operatoren

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#17]
## Description
Für das Struct Color einige wichtige Operatoren implementieren.

## Details
Projekt: "ecm.dll"
Datei: "color.h"
Namespace: "ecm"

## Tasks
- [x] Color ==(Color, Color)
- [x] Color !=(Color, Color)
- [x] Color +(Color, Color)
- [x] Color -(Color, Color)
- [x] Color *(Color, Color)
- [x] Color +=(Color, Color)
- [x] Color -=(Color, Color)
- [x] Color *=(Color, Color)
