### ISSUE TITLE
ColorF-Struct Operatoren

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#18]
## Description
Für das Struct ColorF einige wichtige Operatoren implementieren.

## Details
Projekt: "ecm.dll"
Datei: "color.h"
Namespace: "ecm"

## Tasks
- [ ] ColorF ==(ColorF, ColorF)
- [ ] ColorF !=(ColorF, ColorF)
- [ ] ColorF +(ColorF, ColorF)
- [ ] ColorF -(ColorF, ColorF)
- [ ] ColorF *(ColorF, ColorF)
- [ ] ColorF +=(ColorF, ColorF)
- [ ] ColorF -=(ColorF, ColorF)
- [ ] ColorF *=(ColorF, ColorF)
