### ISSUE TITLE
ANSI Konsolen Attribute erweitern

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#23]
## Description
Weitere ANSI Konsolen Attribute hizufügen, wie Bold, Italic und co.

[Nachschlag hier](https://en.wikipedia.org/wiki/ANSI_escape_code)

## Details
Projekt: "ecm.dll"
Datei: "ecm_console.h"
Namespace: "ecm"

## Tasks
- [x] inline constexpr variablen bold
- [x] inline constexpr variablen italic
- [x] inline constexpr variablen Semitransparent
- [x] inline constexpr variablen underlined
- [x] inline constexpr variablen slowblink
- [x] inline constexpr variablen rapidblink
- [x] inline constexpr variablen swapped
- [x] inline constexpr variablen invisible
