### ISSUE TITLE
Struct Vector2 Implementieren

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#24]
## Description
Das Struct Vector2 implementieren, mit den ersten notwendigen Methoden und Variablen.
Vairablen als Union mit Array, X/Y und W/H.

## Details
Projekt: "ecm.dll"
Datei: "Vector2.h"
Namespace: "ecm::math"

## Tasks
- [x] Struct Vector2
- [x] Enum für Axis
- [x] Variables in a union: 2 float32, 2 float32, float32[2]
- [x] Default-Constructor
- [x] Constructor with 2 float32
- [x] Constructor with float32[2]
