### ISSUE TITLE
Basic Vector2 struct

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#25]
## Description
Das Struct Vector2 implementieren, mit 2 float32 für die x und y Koordinate.
Enumeration für die Axis ist noch sinnvoll.

## Details
Projekt: "ecm.dll"
Datei: "vector2.h" "vector2.cpp"
Namespace: "ecm::math"

## Tasks
- [x] Struct Vector2 implementieren
- [x] Variables in a union: 2 float32, float32[2]
- [x] Default-Constructor
- [x] Constructor with 2 float32
- [x] Constructor with float32 Pointer
