### ISSUE TITLE
Basic Vector2 operators

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#26]
## Description
Für das basis Struct Vector2 einige wichtige Operatoren implementieren.

## Details
Projekt: "ecm.dll"
Datei: "vector2.h" "vector2.cpp"
Namespace: "ecm"

## Tasks
- [x] Vector2 ==(Vector2, Vector2)
- [x] Vector2 !=(Vector2, Vector2)
- [x] Vector2 +(Vector2, Vector2)
- [x] Vector2 -(Vector2, Vector2)
- [x] Vector2 *(Vector2, Vector2)
- [x] Vector2 /(Vector2, Vector2)
- [x] Vector2 +=(Vector2, Vector2)
- [x] Vector2 -=(Vector2, Vector2)
- [x] Vector2 *=(Vector2, Vector2)
- [x] Vector2 /=(Vector2, Vector2)
