### ISSUE TITLE
Basic Vector2i struct

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#27]
## Description
Das Struct Vector2i implementieren, mit 2 float32 für die x und y Koordinate.
Enumeration für die Axis ist noch sinnvoll.

## Details
Projekt: "ecm.dll"
Datei: "vector2i.h" "vector2i.cpp"
Namespace: "ecm"

## Tasks
- [x] Struct Vector2i implementieren
- [x] Variables in a union: 2 float32, float32[2]
- [x] Default-Constructor
- [x] Constructor with 2 float32
- [x] Constructor with float32 Pointer
