### ISSUE TITLE
Basic Vector2i operators

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#28]
## Description
Für das basis Struct Vector2i einige wichtige Operatoren implementieren.

## Details
Projekt: "ecm.dll"
Datei: "vector2i.h" "vector2i.cpp"
Namespace: "ecm"

## Tasks
- [ ] Vector2i ==(Vector2i, Vector2i)
- [ ] Vector2i !=(Vector2i, Vector2i)
- [ ] Vector2i +(Vector2i, Vector2i)
- [ ] Vector2i -(Vector2i, Vector2i)
- [ ] Vector2i *(Vector2i, Vector2i)
- [ ] Vector2i /(Vector2i, Vector2i)
- [ ] Vector2i +=(Vector2i, Vector2i)
- [ ] Vector2i -=(Vector2i, Vector2i)
- [ ] Vector2i *=(Vector2i, Vector2i)
- [ ] Vector2i /=(Vector2i, Vector2i)
