### ISSUE TITLE
Basic Vector3 struct

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#29]
## Description
Das Struct Vector3 implementieren, mit 3 float32 für die x, y und z Koordinaten.
Enumeration für die Axis ist noch sinnvoll.

## Details
Projekt: "ecm.dll"
Datei: "vector3.h" "vector3.cpp"
Namespace: "ecm"

## Tasks
- [x] Struct Vector3 implementieren
- [x] Variables in a union: 3 float32, float32[3]
- [x] Default-Constructor
- [x] Constructor with 3 float32
- [x] Constructor with float32 Pointer
