### ISSUE TITLE
Basic Vector3 operators

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#31]
## Description
Für das basis Struct Vector3 einige wichtige Operatoren implementieren.

## Details
Projekt: "ecm.dll"
Datei: "vector3.h" "vector3.cpp"
Namespace: "ecm"

## Tasks
- [x] Vector3 ==(Vector3, Vector3)
- [x] Vector3 !=(Vector3, Vector3)
- [x] Vector3 +(Vector3, Vector3)
- [x] Vector3 -(Vector3, Vector3)
- [x] Vector3 *(Vector3, Vector3)
- [x] Vector3 /(Vector3, Vector3)
- [x] Vector3 +=(Vector3, Vector3)
- [x] Vector3 -=(Vector3, Vector3)
- [x] Vector3 *=(Vector3, Vector3)
- [x] Vector3 /=(Vector3, Vector3)
