### ISSUE TITLE
Basic Vector4 struct

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#33]
## Description
Das Struct Vector4 implementieren, mit 4 float32 für die x, y, z und w Koordinate.
Enumeration für die Axis ist noch sinnvoll.

## Details
Projekt: "ecm.dll"
Datei: "vector4.h" "vector4.cpp"
Namespace: "ecm"

## Tasks
- [x] Struct Vector4 implementieren
- [x] Variables in a union: 4 float32, float32[4]
- [x] Default-Constructor
- [x] Constructor with 4 float32
- [x] Constructor with float32 Pointer
