### ISSUE TITLE
Basic Vector4 operators

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#34]
## Description
Für das basis Struct Vector4 einige wichtige Operatoren implementieren.

## Details
Projekt: "ecm.dll"
Datei: "vector4.h" "vector4.cpp"
Namespace: "ecm"

## Tasks
- [x] Vector4 ==(Vector4, Vector4)
- [x] Vector4 !=(Vector4, Vector4)
- [x] Vector4 +(Vector4, Vector4)
- [x] Vector4 -(Vector4, Vector4)
- [x] Vector4 *(Vector4, Vector4)
- [x] Vector4 /(Vector4, Vector4)
- [x] Vector4 +=(Vector4, Vector4)
- [x] Vector4 -=(Vector4, Vector4)
- [x] Vector4 *=(Vector4, Vector4)
- [x] Vector4 /=(Vector4, Vector4)
