### ISSUE TITLE
Basic Matrix4x4 struct

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#36]
## Description
Das Struct Matrix4x4 implementieren, mit einem 1D float32 array mit der Größe 16.

## Details
Projekt: "ecm.dll"
Datei: "matrix4x4.h" "matrix4x4.cpp"
Namespace: "ecm::math"

## Tasks
- [x] Struct Matrix4x4 implementieren
- [x] Variablen/Typen in union: struct mit 16 float32 Werten, float32[4][4], float32[16]
- [x] Default-Constructor
- [x] Constructor with float32
- [x] Constructor with float32[16]
- [x] Constructor with float32[4][4]
- [x] Constructor with all 16 floats
- [x] Define Matrix4x4A with align of 16 bytes
