### ISSUE TITLE
Basic Matrix4x4 operators

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#37]
## Description
Für das basis Struct Matrix4x4 einige grundlegende Operatoren implementieren.

## Details
Projekt: "ecm.dll"
Datei: "matrix4x4.h" "matrix4x4.cpp"
Namespace: "ecm::math"

## Tasks
- [x] Matrix4x4 ==(Matrix4x4, Matrix4x4)
- [x] Matrix4x4 !=(Matrix4x4, Matrix4x4)
- [x] Matrix4x4 +(Matrix4x4, Matrix4x4)
- [x] Matrix4x4 -(Matrix4x4, Matrix4x4)
- [x] Matrix4x4 *(Matrix4x4, Matrix4x4)
- [x] Matrix4x4 +=(Matrix4x4, Matrix4x4)
- [x] Matrix4x4 -=(Matrix4x4, Matrix4x4)
- [x] Matrix4x4 *=(Matrix4x4, Matrix4x4)
