### ISSUE TITLE
Matrix4x4 cpp inhalt in inl verschieben und alles inline setzen

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#40]
## Description
Für eine, in zukunft leistungsfähige Bibliothek, sollten die mathematischen Funktionen, vor allem die welche oft verwendet werden, als inline constexpr gekennzeichnet werden und in die .hpp und .inl definitiert und implementiert werden. Die .cpp sollte dann entfernt und die .h zu einer .hpp umbenannt werden.

## Details
Projekt: "ecm.dll"
Datei: "matrix4x4.hpp" "matrix4x4.inl"
Namespace: "ecm::math"

## Tasks
- [x] matrix4x4.h zu matrix4x4.hpp umbenennen
- [x] In der math.hpp die neuen .hpp Dateinamen eintragen
- [x] matrix4x4.hpp Funktionsdefinitionen extern und export entfernen und zu inline constexpr modifizieren
- [x] matrix4x4.inl erstellen und Funktionsimplementierungen übertragen
