### ISSUE TITLE
Vector2 float32 operators

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#49]
## Description
The basic float32 operators for the Vector2 struct.

## Details
Projekt: "ecm.dll"
Datei: "vector2.hpp" "vector2.inl"
Namespace: "ecm"

## Tasks
- [x] Vector2 +(Vector2, float32)
- [x] Vector2 -(Vector2, float32)
- [x] Vector2 *(Vector2, float32)
- [x] Vector2 /(Vector2, float32)
- [x] Vector2 +=(Vector2, float32)
- [x] Vector2 -=(Vector2, float32)
- [x] Vector2 *=(Vector2, float32)
- [x] Vector2 /=(Vector2, float32)
