### ISSUE TITLE
Vector3 float32 operators

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#50]
## Description
The basic float32 operators for the Vector3 struct.

## Details
Projekt: "ecm.dll"
Datei: "vector3.hpp" "vector3.inl"
Namespace: "ecm"

## Tasks
- [x] Vector3 +(Vector3, float32)
- [x] Vector3 -(Vector3, float32)
- [x] Vector3 *(Vector3, float32)
- [x] Vector3 /(Vector3, float32)
- [x] Vector3 +=(Vector3, float32)
- [x] Vector3 -=(Vector3, float32)
- [x] Vector3 *=(Vector3, float32)
- [x] Vector3 /=(Vector3, float32)
