### ISSUE TITLE
Vector4 float32 operators

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#51]
## Description
The basic float32 operators for the Vector4 struct.

## Details
Projekt: "ecm.dll"
Datei: "vector4.hpp" "vector4.inl"
Namespace: "ecm"

## Tasks
- [x] Vector4 +(Vector4, float32)
- [x] Vector4 -(Vector4, float32)
- [x] Vector4 *(Vector4, float32)
- [x] Vector4 /(Vector4, float32)
- [x] Vector4 +=(Vector4, float32)
- [x] Vector4 -=(Vector4, float32)
- [x] Vector4 *=(Vector4, float32)
- [x] Vector4 /=(Vector4, float32)
