### ISSUE TITLE
Project restructure

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#53]
## Description
The solution should be restructured.
New project for math library that will be a static library for inline functions and methods.
One directory for the ecm link and source files and all project files for visual studio should be placed in the root directory named `libs`.

## Details
Projekt: -
Datei: -
Namespace: -

## Tasks
- [x] All include files in one library directory
- [x] All source files in one library directory
- [x] All visual studio project files in the root directory
- [x] Edit the paths in the visual studio project files
- [x] Change the names for the resource files and place them in a rsc directory
