### ISSUE TITLE
Math: Change Vector2 to templated Vector2

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#70]
## Description
Restructure the Vector2 struct to a Vector2_Base template struct, with same variables, 2 _Ty for x and y axis.
Hold the enumeration for the axis.
At end, add a struct Vector2 and a struct Vector2i with using Vector2_Base with the types float32 and int32.

## Details
Projekt: "ecm.math.dll"
Datei: "vector2.hpp" "vector2.inl"
Namespace: "ecm::math"

## Tasks
- [x] Restructure struct Vector2 to Vector2_Base
	- [x] Remove all inline, only constexpr functions/methods
	- [x] Add the template <typename _Ty>
	- [x] Change variables type from float32 to _Ty
	- [x] Add a index operator with uint8 to the struct for the axis
	- [x] Add Vector2, Vector2A, Vector2i and Vector2iA definitions
- [x] Edit the default operators
	- [x] Vector2_Base: Vector2_Base == Vector2_Base
	- [x] Vector2_Base: Vector2_Base != Vector2_Base
	- [x] Vector2_Base: Vector2_Base + Vector2_Base
	- [x] Vector2_Base: Vector2_Base - Vector2_Base
	- [x] Vector2_Base: Vector2_Base * Vector2_Base
	- [x] Vector2_Base: Vector2_Base / Vector2_Base
	- [x] Vector2_Base: Vector2_Base += Vector2_Base
	- [x] Vector2_Base: Vector2_Base -= Vector2_Base
	- [x] Vector2_Base: Vector2_Base *= Vector2_Base
	- [x] Vector2_Base: Vector2_Base /= Vector2_Base
- [x] Edit the vector/float operators
	- [x] Vector2_Base: Vector2_Base + float32
	- [x] Vector2_Base: Vector2_Base - float32
	- [x] Vector2_Base: Vector2_Base * float32
	- [x] Vector2_Base: Vector2_Base / float32
	- [x] Vector2_Base: Vector2_Base += float32
	- [x] Vector2_Base: Vector2_Base -= float32
	- [x] Vector2_Base: Vector2_Base *= float32
	- [x] Vector2_Base: Vector2_Base /= float32
