### ISSUE TITLE
Math: Change Vector3 to templated Vector3

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#72]
## Description
Restructure the Vector3 struct to a Vector3_Base template struct, with same variables, 3 _Ty for x, y and z axis.
Hold the enumeration for the axis.
At end, add a struct Vector3 and a struct Vector3i with using Vector3_Base with the types float32 and int32.

## Details
Projekt: "ecm.math.dll"
Datei: "Vector3.hpp" "Vector3.inl"
Namespace: "ecm::math"

## Tasks
- [ ] Restructure struct Vector3 to Vector3_Base
	- [ ] Remove all inline, only constexpr functions/methods
	- [ ] Add the template <typename _Ty>
	- [ ] Change variables type from float32 to _Ty
	- [ ] Add a index operator with uint8 to the struct for the axis
	- [ ] Add Vector3, Vector3A, Vector3i and Vector3iA definitions
- [ ] Edit the default operators
	- [ ] Vector3_Base: Vector3_Base == Vector3_Base
	- [ ] Vector3_Base: Vector3_Base != Vector3_Base
	- [ ] Vector3_Base: Vector3_Base + Vector3_Base
	- [ ] Vector3_Base: Vector3_Base - Vector3_Base
	- [ ] Vector3_Base: Vector3_Base * Vector3_Base
	- [ ] Vector3_Base: Vector3_Base / Vector3_Base
	- [ ] Vector3_Base: Vector3_Base += Vector3_Base
	- [ ] Vector3_Base: Vector3_Base -= Vector3_Base
	- [ ] Vector3_Base: Vector3_Base *= Vector3_Base
	- [ ] Vector3_Base: Vector3_Base /= Vector3_Base
- [ ] Edit the vector/float operators
	- [ ] Vector3_Base: Vector3_Base + float32
	- [ ] Vector3_Base: Vector3_Base - float32
	- [ ] Vector3_Base: Vector3_Base * float32
	- [ ] Vector3_Base: Vector3_Base / float32
	- [ ] Vector3_Base: Vector3_Base += float32
	- [ ] Vector3_Base: Vector3_Base -= float32
	- [ ] Vector3_Base: Vector3_Base *= float32
	- [ ] Vector3_Base: Vector3_Base /= float32
