### ISSUE TITLE
Add a first simple docs->style markdown documentation

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#75]
## Description
A first and simple documentation, that describes how the code have to looks like.
Styles for function-/variable-names, where the brackets are in code blocks, maximum char limit per lin and so on.

## Details
Datei: "how-to-style-code.md"

## Tasks
- [ ] Name definitions
- [ ] Brackets (which line, same line or next line)
- [ ] Chars limit per line
- [ ] How to comment functions/methods
- [ ] Amount of spaces and where they have to be
