### ISSUE TITLE
Math: Change Vector4 to templated Vector4

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#85]
## Description
Restructure the Vector4 struct to a Vector4_Base template struct, with same variables, 4 _Ty for x, y, z and w axis.
Hold the enumeration for the axis.
At end, add a struct Vector4 and a struct Vector4i with using Vector4_Base with the types float32 and int32.

## Details
Projekt: "ecm.math.dll"
Datei: "Vector4.hpp" "Vector4.inl"
Namespace: "ecm::math"

## Tasks
- [x] Restructure struct Vector4 to Vector4_Base
	- [x] Remove all inline, only constexpr functions/methods
	- [x] Add the template <typename _Ty>
	- [x] Change variables type from float32 to _Ty
	- [x] Add a index operator with uint8 to the struct for the axis
	- [x] Add Vector4, Vector4A, Vector4i and Vector4iA definitions
- [x] Edit the default operators
	- [x] Vector4_Base: Vector4_Base == Vector4_Base
	- [x] Vector4_Base: Vector4_Base != Vector4_Base
	- [x] Vector4_Base: Vector4_Base + Vector4_Base
	- [x] Vector4_Base: Vector4_Base - Vector4_Base
	- [x] Vector4_Base: Vector4_Base * Vector4_Base
	- [x] Vector4_Base: Vector4_Base / Vector4_Base
	- [x] Vector4_Base: Vector4_Base += Vector4_Base
	- [x] Vector4_Base: Vector4_Base -= Vector4_Base
	- [x] Vector4_Base: Vector4_Base *= Vector4_Base
	- [x] Vector4_Base: Vector4_Base /= Vector4_Base
- [x] Edit the vector/float operators
	- [x] Vector4_Base: Vector4_Base + float32
	- [x] Vector4_Base: Vector4_Base - float32
	- [x] Vector4_Base: Vector4_Base * float32
	- [x] Vector4_Base: Vector4_Base / float32
	- [x] Vector4_Base: Vector4_Base += float32
	- [x] Vector4_Base: Vector4_Base -= float32
	- [x] Vector4_Base: Vector4_Base *= float32
	- [x] Vector4_Base: Vector4_Base /= float32
