### ISSUE TITLE
Struct Color implementieren

### ISSUE THREAD

**Issue by AlBuSoft** [Fuerth-ORG/Extended-C-Module#9]
## Description
Das Struct Color implementieren, einmal mit uint8 und einmal mit float32.
Für beide structe jeweils eine Methode um zu anderen zu konvertieren.
`color = (r << 24) | (g << 16) | (b << 8) | a;`
`r = (color >> 24) & 0xFF`;

## Details
Projekt: "ecm.dll"
Datei: "color.h"
Namespace: "ecm"

## Tasks
- [x] **Struct Color**
- [x] Variables in a union: 4 uint8, uint8[4]
- [x] Default-Constructor
- [x] Constructor with 4 uint8
- [x] Constructor with uint32
- [x] Methode ToRGBA32()
- [x] Methode ToRGBA32F()
- [x] **Struct ColorF**
- [x] Variables in a union: 4 float32, float32[4]
- [x] Default-Constructor
- [x] Constructor with 4 float32
- [x] Constructor with uint32
- [x] Methode ToRGBA32()
- [x] Methode ToRGBA8888()
